// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AtoZflix_class;

/************************************************************/
/**
 * 
 */
public class Actors {
	/**
	 * 
	 */
	public int actor_id;
	/**
	 * 
	 */
	public String actor_name;
	/**
	 * 
	 */
	public String charachter_name;

	/**
	 * 
	 * @param actor_id 
	 */
	public void searchActor(undef actor_id) {
	}
}
