// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AtoZflix_class;

/************************************************************/
/**
 * 
 */
public class Admin extends Users {
	/**
	 * 
	 */
	public User user;

	/**
	 * 
	 */
	public void addMovie() {
	}

	/**
	 * 
	 */
	public void deleteMovie() {
	}

	/**
	 * 
	 */
	public void UpdateMovie() {
	}

	/**
	 * 
	 */
	public void AddUser() {
	}

	/**
	 * 
	 */
	public void UpdateUser() {
	}

	/**
	 * 
	 */
	public void deleteUser() {
	}
}
