// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AtoZflix_class;

/************************************************************/
/**
 * 
 */
public class Crew {
	/**
	 * 
	 */
	public int crew_id;
	/**
	 * 
	 */
	public String crew_name;
	/**
	 * 
	 */
	public String job_title;

	/**
	 * 
	 */
	public void searchCrew() {
	}
}
