// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AtoZflix_class;

/************************************************************/
/**
 * 
 */
public class Genres {
	/**
	 * 
	 */
	public int genre_id;
	/**
	 * 
	 */
	public int genre_name;

	/**
	 * 
	 */
	public void searchGenre() {
	}
}
