// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AtoZflix_class;

/************************************************************/
/**
 * 
 */
public class Movies {
	/**
	 * 
	 */
	public int movie_id;
	/**
	 * 
	 */
	public String title;
	/**
	 * 
	 */
	public int budget;
	/**
	 * 
	 */
	public EDate released_date;
	/**
	 * 
	 */
	public int revenue;
	/**
	 * 
	 */
	public String overview;
	/**
	 * 
	 */
	public float rating_avg;
	/**
	 * 
	 */
	public int rating_count;
	/**
	 * 
	 */
	public String country;
	/**
	 * 
	 */
	public String backdrop_path;
	/**
	 * 
	 */
	public String poster_path;
	/**
	 * 
	 */
	public boolean adult;
	/**
	 * 
	 */
	public Actors[] actors;
	/**
	 * 
	 */
	public Genres[] genres;
	/**
	 * 
	 */
	public Crew[] crew;
	/**
	 * 
	 */
	public Favourites[] favourites;
	/**
	 * 
	 */
	public WatchLater[] watchlater;
	/**
	 * 
	 */
	public Admin admin;

	/**
	 * 
	 * @param movie_id 
	 */
	public void showMovieDetails(undef movie_id) {
	}

	/**
	 * 
	 * @param rating_avg 
	 */
	public void sortByRating(undef rating_avg) {
	}

	/**
	 * 
	 * @param released_date 
	 */
	public void sortByRelease(undef released_date) {
	}
}
