// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AtoZflix_class;

/************************************************************/
/**
 * 
 */
public class Ratings {
	/**
	 * 
	 */
	public int rating_id;
	/**
	 * 
	 */
	public int user_id;
	/**
	 * 
	 */
	public int movie_id;
	/**
	 * 
	 */
	public int rating;
	/**
	 * 
	 */
	public String review;
	/**
	 * 
	 */
	public EDate rated_at;
	/**
	 * 
	 */
	public User[] users;

	/**
	 * 
	 */
	public void showRatings() {
	}
}
