// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AtoZflix_class;

/************************************************************/
/**
 * 
 */
public class Users {
	/**
	 * 
	 */
	public int user_id;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public String username;
	/**
	 * 
	 */
	public String password;
	/**
	 * 
	 */
	public String role;
}
