// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AtoZflix_class;

/************************************************************/
/**
 * 
 */
public class WatchLater {
	/**
	 * 
	 */
	public int user_id;
	/**
	 * 
	 */
	public int movie_id;
	/**
	 * 
	 */
	public EDate added_at;

	/**
	 * 
	 */
	public void showWatchLater() {
	}
}
